In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("D:\kunal_cdac_blr_notes\Regression.csv")
df1=df.copy()

In [4]:
df1

,SUMMARY OUTPUT,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Regression Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Multiple R,0.233342,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R Square,0.054448489,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjusted R Square,-0.125656561,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Standard Error,78.06231148,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Observations,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ANOVA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,df,SS,MS,F,Significance F,NaN,NaN,NaN
10,Regression,4,7368.901427,1842.225357,0.302315171,0.873105459,NaN,NaN,NaN
11,Residual,21,127968.214,6093.724474,NaN,NaN,NaN,NaN,NaN
12,Total,25,135337.1154,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Coefficients,Standard Error,t Stat,P-value,Lower 95%,Upper 95%,Lower 95.0%,Upper 95.0%
15,Intercept,149.0878309,50.43056784,2.956298873,0.00753689,44.21172379,253.963938,44.21172379,253.963938
16,f1,0.259422518,0.577509405,0.449209166,0.657882481,-0.941574036,1.460419072,-0.941574036,1.460419072
17,f2,0.092691298,0.541859054,0.171061639,0.865812828,-1.034166292,1.219548888,-1.034166292,1.219548888
18,f3,0.002119158,0.794767032,0.002666389,0.9978977,-1.650689365,1.65492768,-1.650689365,1.65492768
19,f4,0.467782456,0.710341275,0.658531994,0.517351967,-1.009453094,1.945018006,-1.009453094,1.945018006
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,RESIDUAL OUTPUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Observation,Predicted Taget,Residuals,NaN,NaN,NaN,NaN,NaN,NaN
26,1,168.453009,-38.45300902,NaN,NaN,NaN,NaN,NaN,NaN
27,2,162.6396896,-12.63968964,NaN,NaN,NaN,NaN,NaN,NaN
28,3,174.4367375,-14.43673752,NaN,NaN,NaN,NaN,NaN,NaN
29,4,166.7791645,-46.77916449,NaN,NaN,NaN,NaN,NaN,NaN
30,5,187.8014493,7.198550668,NaN,NaN,NaN,NaN,NaN,NaN
31,6,199.3581103,0.641889739,NaN,NaN,NaN,NaN,NaN,NaN
32,7,187.434992,42.56500804,NaN,NaN,NaN,NaN,NaN,NaN
33,8,200.0613066,-20.06130656,NaN,NaN,NaN,NaN,NaN,NaN
34,9,168.8896117,1.110388278,NaN,NaN,NaN,NaN,NaN,NaN
35,10,193.7370704,56.26292961,NaN,NaN,NaN,NaN,NaN,NaN
36,11,224.4649599,-159.4649599,NaN,NaN,NaN,NaN,NaN,NaN
37,12,167.3628791,-17.36287907,NaN,NaN,NaN,NaN,NaN,NaN
38,13,171.6824515,-21.68245153,NaN,NaN,NaN,NaN,NaN,NaN
39,14,205.0028311,24.99716891,NaN,NaN,NaN,NaN,NaN,NaN
40,15,183.9884034,-55.98840335,NaN,NaN,NaN,NaN,NaN,NaN
41,16,201.600977,-47.60097698,NaN,NaN,NaN,NaN,NaN,NaN
42,17,206.2823316,-50.28233163,NaN,NaN,NaN,NaN,NaN,NaN
43,18,166.6031342,73.3968658,NaN,NaN,NaN,NaN,NaN,NaN
44,19,219.5063939,82.49360612,NaN,NaN,NaN,NaN,NaN,NaN
45,20,196.6396741,93.3603259,NaN,NaN,NaN,NaN,NaN,NaN
46,21,176.4182392,-91.41823925,NaN,NaN,NaN,NaN,NaN,NaN
47,22,180.0081654,-124.0081654,NaN,NaN,NaN,NaN,NaN,NaN
48,23,194.3192859,65.68071413,NaN,NaN,NaN,NaN,NaN,NaN
49,24,182.521727,177.478273,NaN,NaN,NaN,NaN,NaN,NaN
50,25,207.9518562,22.04814381,NaN,NaN,NaN,NaN,NaN,NaN
51,26,187.0555496,52.94445035,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df1.drop(columns=['name'])

KeyError: "['name'] not found in axis"

In [ ]:
bais=np.array([1,1,1,1])
val1=np.array([,[df1["f1"].to_numpy(),df["f2"].to_numpy(),df["f3"].to_numpy(),df["f4"].to_numpy()]])

In [ ]:
val1

In [44]:
y

array(['Target'], dtype='<U6')

In [46]:
trasposeval=val1.T
trasposeval

array([[[10],
        [80],
        [ 0],
        [20]],

       [[20],
        [90],
        [10],
        [ 0]],

       [[ 0],
        [20],
        [50],
        [50]],

       [[50],
        [ 0],
        [20],
        [10]],

       [[65],
        [94],
        [19],
        [28]],

       [[80],
        [25],
        [32],
        [58]],

       [[25],
        [64],
        [95],
        [55]],

       [[85],
        [28],
        [62],
        [56]],

       [[40],
        [40],
        [49],
        [12]],

       [[20],
        [20],
        [87],
        [80]],

       [[94],
        [94],
        [84],
        [90]],

       [[25],
        [25],
        [55],
        [20]],

       [[64],
        [64],
        [28],
        [ 0]],

       [[28],
        [49],
        [65],
        [94]],

       [[58],
        [87],
        [45],
        [25]],

       [[55],
        [84],
        [25],
        [65]],

       [[56],
        [55],
        [69],
        [80]],

       [[12],
        [28],
        [53],
        [25]],

       [[98],
        [55],
        [64],
        [85]],

       [[91],
        [56],
        [20],
        [40]],

       [[65],
        [12],
        [ 0],
        [20]],

       [[54],
        [40],
        [50],
        [28]],

       [[95],
        [20],
        [10],
        [40]],

       [[59],
        [94],
        [28],
        [20]],

       [[48],
        [25],
        [58],
        [94]],

       [[78],
        [64],
        [50],
        [25]]], dtype=int64)

In [48]:
new=val1.dot(trasposeval)

ValueError: shapes (1,4,26) and (26,4,1) not aligned: 26 (dim 2) != 4 (dim 1)